#!/usr/bin/env perl

=pod

=head1 NAME

git-verify - Verify server configuration settings.

=head1 SYNOPSIS

  git-verify [ gituser@remote-git-server-host-name.com ] [ /path/to/server/repo.git ... ]

=head1 DESCRIPTION

Command-line utility to verify git server configuration for capabilities that could be used by git-server.

If no remote server is provided, then checks the current server where the command is run.

If no repos are specified, then the home directory is scanned for them.

=head1 TODO

    * Only allow safe read-only operations appropriate for REMOTE_USER powers
    * Scripts and hooks installations
    * Secured ~/.ssh/authorized_keys format, including "KEY" or "REMOTE_USER" settings
    * Files and Directories chmod permissions
    * ADMIN and ACL Management (if "ADMIN")
    * List / Create / Remove repos
    * SSHD Settings
      1. "AcceptEnv XMODIFIERS" in case they want
          to allow "--server-option" and/or "--push-option" and/or "-o" to have
          $GIT_OPTION_COUNT and $GIT_OPTION_{NUM} to be available during pre-* hooks
          or "git-deploy --max-delay <seconds>" for custom push notification timeout
          or "git-client -O <name=val>"
          or other DEBUG features
      2. "AllowAgentForwarding yes" for proxy.url two-way auto-sync feature
      3. "ExposeAuthInfo yes" to allow hooks to obtain public key info, if desired
      4. Enable "any-user"@server feature, if desired.

=head1 AUTHOR

Rob Brown <bbb@cpan.org>

=head1 COPYRIGHT AND LICENSE

Copyright 2025-2026 by Rob Brown <bbb@cpan.org>

This library is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut

use strict;
use warnings;

our $VERSION = "0.037";

if (@ARGV) {
    $ARGV[0] or die "Bad arg\n";
    $ARGV[0] =~ m{/} or exec "ssh", shift, "git-verify", map { m{/} ? $_ : "./$_" } @ARGV or die "$0: remote verification failed.\n";
}

my @repo_dirs = @ARGV;
if (!@repo_dirs) {
    local $_ = $ENV{SSH_ORIGINAL_COMMAND} || "";
    s{^\S+\s+(.+)}{$1};
    @repo_dirs = split;
}

sub run_how_cmd {
    my $stderr = shift;
    my @cmd = @_;
    if (my $pid = open my $fh_out, "-|") {
        # Parent process waiting for kid to say something
        my $output = join "", <$fh_out>;
        waitpid $pid, 0;
        my $exit_status = $?;
        close $fh_out;
        $? = $exit_status;
        return $output;
    }
    # Child process
    open STDERR, $stderr;
    exec @cmd or die "$cmd[0]: Failed to spawn? $!\n";
}

sub run_output_ignore_err {
    return run_how_cmd ">/dev/null", @_;
}

sub run_output_include_err {
    return run_how_cmd ">&STDOUT", @_;
}

#1. Check git-server install
if (eval { require File::Which;1 }) {
    my $bin = File::Which::which("git-server");
    if ($bin) {
        print "git-server found in PATH [$bin]: OK\n";
    }
    elsif (($bin = $0) =~ s/-verify.*/-server/ and -x $bin) {
        print "git-server outside of PATH [$bin]: FAIR\n";
    }
    else {
        print "git-server program missing: BAD\n";
    }
}

#2. Verify SSH Method
if (my $user = $ENV{REMOTE_USER}) {
    if ($ENV{SSH_USER_AUTH}) {
        print "REMOTE_USER: $user: ExposeAuthInfo is enabled: OK\n";
    }
    else {
        print "REMOTE_USER: $user: ExposeAuthInfo is off: FINE\n";
    }
    if ($ENV{SSH_AUTH_SOCK}) {
        if (my @pubkeys = `ssh-add -l 2>/dev/null`) {
            print "REMOTE_USER: $user: AgentForwarding is enabled: OK\n";
        }
        else {
            print "REMOTE_USER: $user: AgentForwarding is mostly enabled, but no pubkeys forwarded: FINE\n";
        }
    }
    else {
        print "REMOTE_USER: $user: AgentForwarding is not configured: FINE\n";
    }
    print "REMOTE_USER: $user: Scanning remote repos with access: OK\n";
}
elsif (!@repo_dirs) {
    print "Commandline scanning $ENV{HOME} for repos: OK\n";
}

#3. Scan repos
if (!@repo_dirs and $ENV{HOME} ||= [getpwuid $<]->[7] and opendir my $fh, $ENV{HOME}) {
    my @nodes = readdir $fh;
    closedir $fh;
    foreach my $node (@nodes) {
        push @repo_dirs, "$ENV{HOME}/$node" if -f "$ENV{HOME}/$node/config" && -d "$ENV{HOME}/$node/refs" && -d "$ENV{HOME}/$node/objects" or -f "$ENV{HOME}/$node/.git/config";
    }
}
my @repo_info;
if (@repo_dirs) {
    foreach my $dir (@repo_dirs) {
        next if $dir =~ /\.workingdir$/;
        my $conf = run_output_include_err "git","-C",$dir,"config","--list","--local";
        my $info = { dir => $dir, config => $conf };
        my $include = $ENV{REMOTE_ADDR} ? 0 : 1;
        foreach my $setting (qw[acl.readers acl.writers acl.deploy core.bare]) {
            my $name = $setting =~ /^(\w+)\.(\w+)$/ ? $2 : next;
            my $section = $1;
            if ($conf =~ /^\Q$setting\E=(.*)/m) {
                $info->{$name} = $1;
                $include = 1 if !$include and $ENV{REMOTE_USER} and $1 =~ /(^|,)\Q$ENV{REMOTE_USER}\E($|,)/;
            }
            else {
                $info->{$name} = "(missing)";
            }
        }
        push @repo_info, $info if $include;
    }
}
print "Found ".scalar(@repo_info)." repos\n";
if (@repo_info) {
    foreach my $repo (@repo_info) {
        if ($repo->{bare} eq "true") {
            print "$repo->{dir}: Found Bare Repo: OK\n";
        }
        elsif ($repo->{bare} eq "false") {
            if ($repo->{config} =~ m{^remote.*url=(.+)}m) {
                print "$repo->{dir}: Found Working Dir [$1]: FAIR\n";
            }
            else {
                print "$repo->{dir}: Found Non-Bare Hokey Checkout Missing Remote: POOR\n";
            }
        }
        else {
            print "$repo->{dir}: Unrecognized Git Repo: BORKED!\n";
        }
    }
}
