#!/usr/bin/env perl

=pod

=head1 NAME

git-verify - Verify server configuration settings.

=head1 SYNOPSIS

  git-verify [ <REMOTE> ] [ /path/to/server/repo.git ... ]

=head1 DESCRIPTION

Command-line utility to verify git server configuration for capabilities that could be used by git-server.

<REMOTE> can be any valid SCP-style Git URL, such as:

  gituser@remote-git-server-host-name.com:my-repo.git

Or it can be a full ssh:// Git URL, such as:

  ssh://gituser@remote-git-server-host-name.com/my-repo.git

Or if you don't care about any specific repo, then <REMOTE> can use simple ssh-style format, such as:

  gituser@remote-git-server-host-name.com

If no user@ is provided, then ssh will use your current username.

If NO <REMOTE> is provided, then checks the current server where the command is run.

If no repo directories are specified, then the HOME directory is scanned
for any directory that smells like a git repo.

=head1 TODO

    * Only allow safe read-only operations appropriate for REMOTE_USER powers
    * Scripts and hooks installations
    * Secured ~/.ssh/authorized_keys format, including "KEY" or "REMOTE_USER" settings
    * Files and Directories chmod permissions
    * ADMIN and ACL Management (if "ADMIN")
    * List / Create / Remove repos
    * SSHD Settings
      1. "AcceptEnv XMODIFIERS" in case they want
          to allow "--server-option" and/or "--push-option" and/or "-o" to have
          $GIT_OPTION_COUNT and $GIT_OPTION_{NUM} to be available during pre-* hooks
          or "git-deploy --max-delay <seconds>" for custom push notification timeout
          or "git-client -O <name=val>"
          or other DEBUG features
      2. "AllowAgentForwarding yes" for proxy.url two-way auto-sync feature
      3. "ExposeAuthInfo yes" to allow hooks to obtain public key info, if desired
      4. Enable "any-user"@server feature, if desired.

=head1 AUTHOR

Rob Brown <bbb@cpan.org>

=head1 COPYRIGHT AND LICENSE

Copyright 2025-2026 by Rob Brown <bbb@cpan.org>

This library is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut

use strict;
use warnings;
use Cwd qw(abs_path);

our $VERSION = "0.037";

if (@ARGV) {
    local $_ = $ARGV[0] or die "Bad arg\n";
    s{^ssh://(|[^/:]+\@)\[([a-z0-9\-\.\:]+)\]:(\d+)(?:$|/)}{}i ||
    s{^ssh://(|[^/:]+\@)\[?([a-z0-9\-\.]+)\]?:\[?(\d+)\]?(?:$|/)}{}i ||
    s{^ssh://(|[^/:]+\@)\[?([a-z0-9\-\.\:]+)\]?(?:$|/)}{}i ||
    s{^(|[^/:]+\@)\[([a-z0-9\-\.]+):(\d+)\](?:$|:)}{}i ||
    s{^(|[^/:]+\@)\[([a-z0-9\-\.\:]+)\]()(?:$|:)}{}i ||
    s{^(|[^/:]+\@)([a-z0-9\-\.]+)()(?:$|:)}{}i and do {
        my $userprefix = $1;
        my $remotehost = $2;
        my $remoteport = $3 || 22;
        my $resolvable = undef;
        $resolvable = gethostbyname($remotehost) or eval {
            require Socket;
            my ($err, @res) = Socket::getaddrinfo($remotehost,22,{socktype=>Socket::SOCK_STREAM(),family=>Socket::AF_UNSPEC(),flags=>((eval{Socket::AI_ALL()}||0)|(eval{Socket::AI_V4MAPPED()}||0))});
            $resolvable = @res;
            1;
        } or eval {
            require File::Which; # Try "dig" as last-ditch effort:
            my $dig = File::Which::which("dig") or die "no dig";
            $resolvable = `$dig +short $remotehost A $remotehost AAAA 2>/dev/null`;
            1;
        } or $resolvable = 1; # If IPv6 resolvers are unavailable, then assume it's valid, and just blindly run ssh
        if ($resolvable) {
            length?$ARGV[0]=$_:shift;
            exec "ssh","-p",$remoteport,"$userprefix$remotehost","git-verify", map { m{/} ? $_ : "./$_" } @ARGV or die "$0: remote verification failed.\n";
        }
    };
}

my @repo_dirs = @ARGV;
if (!@repo_dirs) {
    local $_ = $ENV{SSH_ORIGINAL_COMMAND} || "";
    s{^\S+\s+(.+)}{$1};
    @repo_dirs = split;
}

sub run_how_cmd {
    my $stderr = shift;
    my @cmd = @_;
    if (my $pid = open my $fh_out, "-|") {
        # Parent process waiting for kid to say something
        my $output = join "", <$fh_out>;
        waitpid $pid, 0;
        my $exit_status = $?;
        close $fh_out;
        $? = $exit_status;
        return $output;
    }
    # Child process
    open STDERR, $stderr;
    exec @cmd or die "$cmd[0]: Failed to spawn? $!\n";
}

sub run_output_ignore_err {
    return run_how_cmd ">/dev/null", @_;
}

sub run_output_include_err {
    return run_how_cmd ">&STDOUT", @_;
}

#1. Check git-server install
if (eval { require File::Which;1 }) {
    my $bin = File::Which::which("git-server");
    if ($bin) {
        print "git-server found in PATH [$bin]: OK\n";
    }
    elsif (($bin = $0) =~ s/-verify.*/-server/ and -x $bin) {
        print "git-server outside of PATH [$bin]: FAIR\n";
    }
    else {
        print "git-server program missing: BAD\n";
    }
}

#2. Verify SSH Method
if (my $user = $ENV{REMOTE_USER}) {
    if ($ENV{SSH_USER_AUTH}) {
        print "REMOTE_USER: $user: ExposeAuthInfo is enabled: OK\n";
    }
    else {
        print "REMOTE_USER: $user: ExposeAuthInfo is off: FINE\n";
    }
    if ($ENV{SSH_AUTH_SOCK}) {
        if (my @pubkeys = `ssh-add -l 2>/dev/null`) {
            print "REMOTE_USER: $user: AgentForwarding is enabled: OK\n";
        }
        else {
            print "REMOTE_USER: $user: AgentForwarding is mostly enabled, but no pubkeys forwarded: FINE\n";
        }
    }
    else {
        print "REMOTE_USER: $user: AgentForwarding is not configured: FINE\n";
    }
    if (my $count = @repo_dirs) {
        print "REMOTE_USER: $user: Filtering $count specified repos for access: OK\n";
    }
    else {
        print "REMOTE_USER: $user: Scanning remote repos with access: OK\n";
    }
}
elsif (!@repo_dirs) {
    print "Commandline scanning $ENV{HOME} for repos: OK\n";
}

#3. Scan repos
-d ($ENV{HOME} ||= [getpwuid $<]->[7]) or die "HOME broken";
if (!@repo_dirs and opendir my $fh, $ENV{HOME}) {
    my @nodes = readdir $fh;
    closedir $fh;
    foreach my $node (@nodes) {
        push @repo_dirs, "$ENV{HOME}/$node" if -f "$ENV{HOME}/$node/config" && -d "$ENV{HOME}/$node/refs" && -d "$ENV{HOME}/$node/objects" or -f "$ENV{HOME}/$node/.git/config";
    }
}
my @repo_info;
if (@repo_dirs) {
    my %seen;
    foreach my $repo (@repo_dirs) {
        $repo =~ s{/+$}{}; # Remove trailing slashes.
        next if $repo =~ /\.workingdir$/;
        my $gitdir = undef;
        if (-d $repo) {
            $gitdir = $repo;
        }
        else {
            $repo =~ s/\.git$//;
            my @check = ("$repo.git/.git", "$repo.git", "$repo/.git", $repo);
            if (0 != index $repo, $ENV{HOME}) { # Not starting with $HOME
                push @check, map { "$ENV{HOME}/$_" } @check; # Try with prepended $HOME too
            }
            foreach (@check) {
                $gitdir = $_ and next if -d;
            }
        }
        next if !$gitdir;
        $gitdir = abs_path $gitdir; # Collapse duplicate slashes. Get rid of any "/./" silly sandwiches. Also removes trailing slashes (although should already be gone by now).
        (my $nice = $gitdir) =~ s{(?:/|\.git)+$}{};
        next if $seen{$nice}++;
        my $conf = run_output_include_err "git","-C",$gitdir,"config","--list","--local";
        my $info = { nice => $nice, dir => $gitdir, config => $conf };
        my $include = $ENV{REMOTE_ADDR} ? 0 : 1;
        foreach my $setting (qw[acl.readers acl.writers acl.deploy core.bare proxy.url]) {
            my $name = $setting =~ /^(\w+)\.(\w+)$/ ? $2 : next;
            my $section = $1;
            if ($conf =~ /^\Q$setting\E=(.*)/m) {
                $info->{$name} = $1;
                $include = 1 if !$include and $ENV{REMOTE_USER} and $1 =~ /(^|,)\Q$ENV{REMOTE_USER}\E($|,)/;
            }
            else {
                $info->{$name} = "";
            }
        }
        push @repo_info, $info if $include;
    }
}
print "Found ".scalar(@repo_info)." repos\n";
if (@repo_info) {
    foreach my $info (@repo_info) {
        if ($info->{bare} eq "true") {
            if (my $proxy = $info->{url}) {
                if (-d "$info->{dir}.workingdir") {
                    print "$info->{nice}: Found Bare Repo proxy linked [$proxy]: OK\n";
                }
                else {
                    print "$info->{nice}: Found Bare Repo with broken proxy [$proxy]: POOR\n";
                }
            }
            else {
                print "$info->{nice}: Found Bare Repo: OK\n";
            }
        }
        elsif ($info->{bare} eq "false") {
            if ($info->{config} =~ m{^remote.*url=(.+)}m) {
                print "$info->{nice}: Found Working Dir [$1]: FAIR\n";
            }
            else {
                print "$info->{nice}: Found Non-Bare Hokey Checkout Missing Remote: POOR\n";
            }
        }
        else {
            print "$info->{nice}: Unrecognized Git Repo: BORKED!\n";
        }
    }
}
