#!/usr/bin/env perl

=pod

=head1 NAME

git-verify - Verify server configuration settings.

=head1 SYNOPSIS

  git-verify [ gituser@remote-git-server-host-name.com ] [ /path/to/server/repo.git ... ]

=head1 DESCRIPTION

Command-line utility to verify git server configuration for capabilities that could be used by git-server.

If no remote server is provided, then checks the current server where the command is run.

If no repos are specified, then the home directory is scanned for them.

=head1 TODO

    * Only allow safe read-only operations appropriate for REMOTE_USER powers
    * Scripts and hooks installations
    * Secured ~/.ssh/authorized_keys format, including "KEY" or "REMOTE_USER" settings
    * Files and Directories chmod permissions
    * ADMIN and ACL Management (if "ADMIN")
    * List / Create / Remove repos
    * SSHD Settings
      1. "AcceptEnv XMODIFIERS" in case they want
          to allow "--server-option" and/or "--push-option" and/or "-o" to have
          $GIT_OPTION_COUNT and $GIT_OPTION_{NUM} to be available during pre-* hooks
          or "git-deploy --max-delay <seconds>" for custom push notification timeout
          or "git-client -O <name=val>"
          or other DEBUG features
      2. "AllowAgentForwarding yes" for proxy.url two-way auto-sync feature
      3. "ExposeAuthInfo yes" to allow hooks to obtain public key info, if desired
      4. Enable "any-user"@server feature, if desired.

=head1 AUTHOR

Rob Brown <bbb@cpan.org>

=head1 COPYRIGHT AND LICENSE

Copyright 2025-2026 by Rob Brown <bbb@cpan.org>

This library is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut

use strict;
use warnings;

our $VERSION = "0.037";

if (@ARGV) {
    $ARGV[0] or die "Bad arg\n";
    $ARGV[0] =~ m{/} or exec "ssh", shift, "git-verify", map { m{/} ? $_ : "./$_" } @ARGV or die "$0: remote verification failed.\n";
}

#1. Check git-server install
if (eval { require File::Which;1 }) {
    my $bin = File::Which::which("git-server");
    if ($bin) {
        print "git-server found in PATH [$bin]: OK\n";
    }
    elsif (($bin = $0) =~ s/-verify.*/-server/ and -x $bin) {
        print "git-server outside of PATH [$bin]: FAIR\n";
    }
    else {
        print "git-server program missing: BAD\n";
    }
}
