#!/usr/bin/perl

use strict;
use warnings;

my $parent = getppid();
my $lock_file = "branches.$parent.locked";

if (-s $lock_file) {
    if (open my $fh, "<", $lock_file) {
        while (<$fh>) {
            chomp;
            unlink $_;
        }
        close $fh;
        unlink $lock_file;
    }
}
