#!/usr/bin/perl

use strict;
use warnings;

my $user = $ENV{KEY} or die "ENV KEY must be set to make changes.\n";
my $r = "\x01"; # enable bit 2^(fileno STDIN)
die "$0: Commandline Execution Worked!\n" if !select $r, undef, undef, 0.2;
my $push_info = <STDIN>;
my ($old,$new,$ref) = $push_info =~ m{^(\w+) (\w+) ([\w/]+)} or die "$0: Invalid syntax!\n";
if ($ref) {
    my $branch = ($ref =~ m{^refs/heads/(.+)} || $ref =~ m{.*/([^/]+)}) ? $1 : $ref;
    if ($old =~ /^0+$/) {
        print localtime().": [$user] Creating new branch [$branch]\n";
    }
    elsif ($new =~ /^0+$/) {
        die localtime().": [$user] Do not delete branch [$branch]\n";
    }
    elsif (`git log $new -- 2>&1 | grep '^commit $old'`) {
        #print localtime().": [$user] Pushing $new changes to [$branch] tip without --force\n";
        # XXX - Do we need to check for restrictedbranch?
    }
    else {
        die localtime().": [$user] You can try 'git pull --rebase' or 'git pull' to clean your local repo, but do not use 'git push --force' on branch: $branch\n";
    }
}
