#!/usr/bin/perl

use strict;
use warnings;

my $acl = {};
my $conf = `git config --list`;
while ($conf =~ s/^acl.(\w+)=(.*)$//m) {
    my $param = $1;
    my $keys = $2;
    foreach my $key (split /,/, $keys) {
        $acl->{$param}->{$key} = 1;
    }
}

my $KEY = $ENV{KEY} || "UNKNOWN";
die "$KEY: You have been banned from all update operations!\n" unless $acl->{writers}->{$KEY};
